spring:
  application:
    name: spring.boot.eureka.client
server:
  port: 8082
eureka:
  client:
    serviceURL:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true